### ISSUE TITLE
EU868|ADR|RX parameters configuration

### ISSUE THREAD

**Issue by noraneto** [helium/router#416] opened 2021-08-27 12:38 UTC
Unbalanced link budget between uplink and downlink causes repeated MAC command downlinks as the device is unable to receive them. The downlink is usually the limiting link and using RX1 data rate offset or RX2 window is recommended.

**Comment by macpie** [comment] 2021-08-30 17:47
The hotspot should be choosing RX2 if it believes it missed RX1.

**Comment by macpie** [comment] 2021-09-01 21:45
I think this is a duplicate of https://github.com/helium/router/issues/391

**Closed by macpie** 2021-09-01 21:45 UTC
Labels: question

**Comment by noraneto** [comment] 2021-09-02 06:14
This is not a duplicate. When device does not receive LINK_ADR_REQ downlink due weak signal it does not respond with LINK_ADR_ANS as in case of #391. RX1 data rate offset is used to balance the uplink and downlink radio link margins. Currently the same data rate is used for uplinks and downlinks.
