### ISSUE TITLE
End-device has difficulty with downlink.

### ISSUE THREAD

**Issue by illperipherals** [helium/router#467] opened 2021-10-26 07:57 UTC
Observation: RX_TIMEOUT interrupt is triggered from the transceiver very often.

Diagnosis: The receiver is detecting enough LoRa symbols and begins to decode but never seems to achieve a lock resulting in the RX_TIMEOUT.  There are several possible reasons one of which is contention.  As mentioned earlier the Helium gateways are operating on FSB2, which is the same as TheThingsNetwork.  This may cause the CAD to recognize LoRa signals from other networks.

End-Device Hack:  Set the “Number of Symbols” parameter to 0.  This seems to have the effect of causing the RX_TIMEOUT interrupt – slightly differing from the documentation.

Preferred Solution: Introduce some more diversity in the network by having Gateways operate in other FSBs.

**Comment by jdgemm** [comment] 2021-11-11 00:17
duplicate of #465

**Closed by jdgemm** 2021-11-11 00:17 UTC
