### ISSUE TITLE
Device data stops flowing when fcnt hits 65535

### ISSUE THREAD

**Issue by mikedsp** [helium/router#801] opened 2022-06-23 11:40 UTC
1. Are you using Helium hosted Console or running your own open source Console?
Helium hosted
2. If you are on Helium hosted Console, which url are you currently on? 
https://console.helium.com/
3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).
org name: mikedsp
Device ID: 218cd2cd-ea47-4fdd-b77c-ab10d9eb9445
Device Name: TBHV1110_2 (Browan Healthy Home Sensor)
Please describe your issue:
When fcnt hit 65535 on June 18, no more data was received from that device. 
This same thing had happened with one of my TBSL100 devices in May. At that time, I reached out the Browan Application Engineer. He reported that they investigated the issue and shared the following results: 
1. Were able to reproduce the issue on the Helium console
2. When tested against the Chirpstack, the frame count went beyond 65535. The attached image is from their Chirpstack test. 
![image](https://user-images.githubusercontent.com/47757569/175290054-952cdb1b-4e6b-4dd7-8652-e19f5aefb7ba.png)
3. They also validated directly on the device that the device supports frame counts > 65535 
![image](https://user-images.githubusercontent.com/47757569/175290414-e3845c3e-3931-4983-a7b6-3547b28875e2.png)

**Comment by macpie** [comment] 2022-06-23 18:20
This is known and will be fixed in https://github.com/helium/router/pull/780

**Comment by macpie** [comment] 2022-06-23 18:20
Duplicate of https://github.com/helium/router/issues/643

**Closed by macpie** 2022-06-23 18:20 UTC
